# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# misc
umask 0022
export LD_LIBRARY_PATH=<%= @conda_path %>/lib:/usr/lib:/usr/lib64:/usr/local/lib:$LD_LIBRARY_PATH
export GIT_SSL_NO_VERIFY=true
export PATH=<%= @conda_path %>/bin:$PATH

# source mozart virtualenv
export MOZART_DIR=$HOME/mozart
source $MOZART_DIR/bin/activate
